# define a default docker image for all jobs
image: node:10.6.0

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - npm install -g serverless@1.27.3
    - serverless deploy
  # This folder is cached between builds
  cache:
    paths:
      - node_modules/