# define a default docker image for all jobs
image: node:latest

stages:
  - deploy

# This folder is cached between builds
cache:
  paths:
  - node_modules/

deploy:
  stage: deploy
  script:
   - npm install -g
   - serverless deploy --stage production