service: quality-mail-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: production #dev
  region: us-east-1
  stackName: quality-mail-service
  apiName: quality-mail-service
  memorySize: 128 #default is 1024
  timeout: 5 #default 6
  endpointType: regional #default is edge
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SES:SendEmail
        - SES:SendTemplatedEmail
        - SES:SendRawEmail
      Resource: "*"
  usagePlan:
    quota:
      limit: 50000
      offset: 0
      period: DAY
    throttle:
      burstLimit: 14
      rateLimit: 14
  stackTags:
    STACK: quality-mail-service

plugins:
  - serverless-webpack
  - serverless-domain-manager

functions:
  sendEmail:
    name: ${self:provider.stage}-sendEmail
    handler: handler.sendEmail
    description: Send email using SES service.
    tags:
      ENDPOINT: send-email
      STACK: quality-mail-service
    events:
      - http:
          path: send-email
          method: post
          integration: lambda
          cors: true
          private: true #Force 'x-api-key' in header
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"

custom:
  customDomain:
    domainName: api.qualitydepiction.com
    basePath: 'v1'
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: regional