service: quality-mail-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: production #dev
  region: us-east-1
  stackName: quality-mail-service
  apiName: quality-mail-service
  memorySize: 512 #default is 1024
  timeout: 5 #default 6
  endpointType: regional #default is edge
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SES:SendEmail
        - SES:SendTemplatedEmail
        - SES:SendRawEmail
      Resource: "*"
  usagePlan:
    quota:
      limit: 50000
      offset: 2
      period: DAY
    throttle:
      burstLimit: 200
      rateLimit: 14
  stackTags:
    stack: quality-mail-service

plugins:
  - serverless-webpack

functions:
  sendEmail:
    name: ${self:provider.stage}-sendEmail
    handler: handler.sendEmail
    description: Send email using SES service.
    tags:
      function: sendEmail
      stack: quality-mail-service
    events:
      - http:
          path: sendEmail
          method: post
          integration: lambda
          cors: true
          private: true #Force 'x-api-key' in header
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"